<?php

namespace Database\Seeders;

use App\Models\AttendanceOccurrence;
use Illuminate\Database\Seeder;

class AttendanceOccurrenceSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Presença',
                'code' => 'present',
                'description' => 'Jornada regular sem intercorrências.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Falta',
                'code' => 'absence',
                'description' => 'Ausência sem justificativa.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Falta Justificada',
                'code' => 'justified_absence',
                'description' => 'Ausência justificada conforme regra da empresa.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Atestado',
                'code' => 'medical_certificate',
                'description' => 'Ausência por atestado médico.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Atestado Acidentário',
                'code' => 'occupational_medical_certificate',
                'description' => 'Ausência por acidente de trabalho com apresentação de atestado.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Atraso',
                'code' => 'lateness',
                'description' => 'Entrada após o horário previsto.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Saída Antecipada',
                'code' => 'early_leave',
                'description' => 'Saída antes do fim da jornada.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Hora Extra 50%',
                'code' => 'overtime_50',
                'description' => 'Horas extras com adicional de 50%.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Hora Extra 60%',
                'code' => 'overtime_60',
                'description' => 'Horas extras com adicional de 60%.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Hora Extra 70%',
                'code' => 'overtime_70',
                'description' => 'Horas extras com adicional de 70%.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Hora Extra 100%',
                'code' => 'overtime_100',
                'description' => 'Horas extras com adicional de 100%.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Adicional Noturno',
                'code' => 'night_shift',
                'description' => 'Período trabalhado em faixa noturna.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Prorrogação Noturna',
                'code' => 'night_extension',
                'description' => 'Prorrogação de jornada após período noturno com reflexo em adicional.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Sobreaviso',
                'code' => 'on_call',
                'description' => 'Regime de sobreaviso.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Prontidão',
                'code' => 'standby',
                'description' => 'Regime de prontidão do colaborador.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Folga',
                'code' => 'day_off',
                'description' => 'Folga programada.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Folga Compensatória',
                'code' => 'compensatory_day_off',
                'description' => 'Folga concedida para compensação de jornada ou banco de horas.',
                'affects_payroll' => false,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'DSR',
                'code' => 'weekly_paid_rest',
                'description' => 'Descanso semanal remunerado.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Feriado',
                'code' => 'holiday',
                'description' => 'Dia de feriado.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Trabalho em Feriado',
                'code' => 'holiday_work',
                'description' => 'Jornada realizada em feriado com reflexo em pagamento ou compensação.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Trabalho em Domingo',
                'code' => 'sunday_work',
                'description' => 'Jornada realizada em domingo com reflexo em pagamento ou compensação.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Compensação',
                'code' => 'compensation',
                'description' => 'Compensação de horas.',
                'affects_payroll' => false,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Banco de Horas Crédito',
                'code' => 'hour_bank_credit',
                'description' => 'Crédito no banco de horas.',
                'affects_payroll' => false,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Banco de Horas Débito',
                'code' => 'hour_bank_debit',
                'description' => 'Débito no banco de horas.',
                'affects_payroll' => false,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Banco de Horas Pago',
                'code' => 'hour_bank_paid',
                'description' => 'Pagamento de horas apuradas no banco de horas.',
                'affects_payroll' => true,
                'affects_hour_bank' => true,
            ],
            [
                'name' => 'Treinamento',
                'code' => 'training',
                'description' => 'Período destinado a treinamento interno ou externo.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Viagem a Serviço',
                'code' => 'business_trip',
                'description' => 'Deslocamento em atividade de serviço.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Serviço Externo',
                'code' => 'external_service',
                'description' => 'Atividade externa vinculada à função do colaborador.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Reunião',
                'code' => 'meeting',
                'description' => 'Período destinado a reunião operacional, administrativa ou de segurança.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Integração',
                'code' => 'integration_training',
                'description' => 'Integração inicial de colaborador ou treinamento admissional.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Parada por Chuva',
                'code' => 'rain_stop',
                'description' => 'Interrupção das atividades em razão de chuva.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Parada Operacional',
                'code' => 'operational_stop',
                'description' => 'Parada de atividade por decisão operacional ou indisponibilidade de frente de trabalho.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Parada por Manutenção',
                'code' => 'maintenance_stop',
                'description' => 'Paralisação por manutenção de equipamento, veículo ou estrutura.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Afastamento INSS',
                'code' => 'social_security_leave',
                'description' => 'Afastamento previdenciário do colaborador.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Licença Maternidade',
                'code' => 'maternity_leave',
                'description' => 'Licença maternidade da colaboradora.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Licença Paternidade',
                'code' => 'paternity_leave',
                'description' => 'Licença paternidade do colaborador.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Licença Casamento',
                'code' => 'marriage_leave',
                'description' => 'Ausência legal em razão de casamento.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Licença Óbito',
                'code' => 'bereavement_leave',
                'description' => 'Ausência legal em razão de falecimento de familiar.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Suspensão',
                'code' => 'suspension',
                'description' => 'Suspensão disciplinar do colaborador.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Advertência',
                'code' => 'warning',
                'description' => 'Registro de advertência sem impacto direto na folha.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Férias',
                'code' => 'vacation',
                'description' => 'Período de gozo de férias.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Abono Pecuniário',
                'code' => 'vacation_bonus_sell',
                'description' => 'Conversão parcial das férias em abono pecuniário.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Licença Não Remunerada',
                'code' => 'unpaid_leave',
                'description' => 'Afastamento sem remuneração.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Falta Parcial',
                'code' => 'partial_absence',
                'description' => 'Ausência parcial durante a jornada com impacto proporcional.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Troca de Turno',
                'code' => 'shift_change',
                'description' => 'Alteração de turno de trabalho sem impacto direto na folha.',
                'affects_payroll' => false,
                'affects_hour_bank' => false,
            ],
            [
                'name' => 'Ajuda de Custo Operacional',
                'code' => 'operational_allowance',
                'description' => 'Registro operacional com possível reflexo informativo para apontamento de campo.',
                'affects_payroll' => true,
                'affects_hour_bank' => false,
            ],
        ];

        foreach ($items as $item) {
            AttendanceOccurrence::updateOrCreate(
                ['code' => $item['code']],
                [
                    'name' => $item['name'],
                    'code' => $item['code'],
                    'description' => $item['description'],
                    'affects_payroll' => $item['affects_payroll'],
                    'affects_hour_bank' => $item['affects_hour_bank'],
                    'is_active' => true,
                ]
            );
        }
    }
}