<?php

namespace Database\Seeders;

use App\Models\PayrollEvent;
use Illuminate\Database\Seeder;

class PayrollEventSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'code' => 'SALARIO_BASE',
                'name' => 'Salário Base',
                'type' => 'earning',
                'incidence_type' => 'salary',
                'calculation_type' => 'fixed',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Evento principal do salário contratual.',
            ],
            [
                'code' => 'HORA_EXTRA_50',
                'name' => 'Hora Extra 50%',
                'type' => 'earning',
                'incidence_type' => 'overtime',
                'calculation_type' => 'quantity_x_value',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Horas extras com adicional de 50%.',
            ],
            [
                'code' => 'HORA_EXTRA_100',
                'name' => 'Hora Extra 100%',
                'type' => 'earning',
                'incidence_type' => 'overtime',
                'calculation_type' => 'quantity_x_value',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Horas extras com adicional de 100%.',
            ],
            [
                'code' => 'ADICIONAL_NOTURNO',
                'name' => 'Adicional Noturno',
                'type' => 'earning',
                'incidence_type' => 'night',
                'calculation_type' => 'quantity_x_value',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Adicional incidente sobre trabalho noturno.',
            ],
            [
                'code' => 'DSR_HE',
                'name' => 'DSR sobre Hora Extra',
                'type' => 'earning',
                'incidence_type' => 'rest',
                'calculation_type' => 'automatic',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Reflexo do descanso semanal remunerado sobre hora extra.',
            ],
            [
                'code' => 'INSALUBRIDADE',
                'name' => 'Adicional de Insalubridade',
                'type' => 'earning',
                'incidence_type' => 'allowance',
                'calculation_type' => 'percentage',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Adicional de insalubridade.',
            ],
            [
                'code' => 'PERICULOSIDADE',
                'name' => 'Adicional de Periculosidade',
                'type' => 'earning',
                'incidence_type' => 'allowance',
                'calculation_type' => 'percentage',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Adicional de periculosidade.',
            ],
            [
                'code' => 'BONIFICACAO',
                'name' => 'Bonificação',
                'type' => 'earning',
                'incidence_type' => 'bonus',
                'calculation_type' => 'manual',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Bonificação eventual.',
            ],
            [
                'code' => 'GRATIFICACAO',
                'name' => 'Gratificação',
                'type' => 'earning',
                'incidence_type' => 'bonus',
                'calculation_type' => 'manual',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Gratificação eventual ou fixa.',
            ],
            [
                'code' => 'COMISSAO',
                'name' => 'Comissão',
                'type' => 'earning',
                'incidence_type' => 'commission',
                'calculation_type' => 'manual',
                'affects_inss' => true,
                'affects_fgts' => true,
                'affects_irrf' => true,
                'affects_net' => true,
                'description' => 'Comissão do colaborador.',
            ],
            [
                'code' => 'FALTA',
                'name' => 'Falta',
                'type' => 'deduction',
                'incidence_type' => 'absence',
                'calculation_type' => 'quantity_x_value',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto por falta.',
            ],
            [
                'code' => 'ATRASO',
                'name' => 'Atraso',
                'type' => 'deduction',
                'incidence_type' => 'lateness',
                'calculation_type' => 'quantity_x_value',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto por atraso.',
            ],
            [
                'code' => 'INSS',
                'name' => 'INSS',
                'type' => 'deduction',
                'incidence_type' => 'social_security',
                'calculation_type' => 'automatic',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto previdenciário do colaborador.',
            ],
            [
                'code' => 'FGTS',
                'name' => 'FGTS',
                'type' => 'base',
                'incidence_type' => 'fund',
                'calculation_type' => 'automatic',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => false,
                'description' => 'Base/valor do FGTS para controle.',
            ],
            [
                'code' => 'IRRF',
                'name' => 'IRRF',
                'type' => 'deduction',
                'incidence_type' => 'income_tax',
                'calculation_type' => 'automatic',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Imposto de renda retido na fonte.',
            ],
            [
                'code' => 'VALE_TRANSPORTE',
                'name' => 'Vale Transporte',
                'type' => 'deduction',
                'incidence_type' => 'benefit',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto ou controle de vale transporte.',
            ],
            [
                'code' => 'VALE_ALIMENTACAO',
                'name' => 'Vale Alimentação',
                'type' => 'deduction',
                'incidence_type' => 'benefit',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto ou controle de vale alimentação.',
            ],
            [
                'code' => 'CESTA_BASICA',
                'name' => 'Cesta Básica',
                'type' => 'deduction',
                'incidence_type' => 'benefit',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto ou controle de cesta básica.',
            ],
            [
                'code' => 'PLANO_SAUDE',
                'name' => 'Plano de Saúde',
                'type' => 'deduction',
                'incidence_type' => 'benefit',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto de plano de saúde.',
            ],
            [
                'code' => 'CONVENIO_FARMACIA',
                'name' => 'Convênio Farmácia',
                'type' => 'deduction',
                'incidence_type' => 'benefit',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto de convênio farmácia.',
            ],
            [
                'code' => 'ADIANTAMENTO_SALARIAL',
                'name' => 'Adiantamento Salarial',
                'type' => 'deduction',
                'incidence_type' => 'advance',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto de adiantamento salarial.',
            ],
            [
                'code' => 'EMPRESTIMO',
                'name' => 'Empréstimo',
                'type' => 'deduction',
                'incidence_type' => 'loan',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto de empréstimo.',
            ],
            [
                'code' => 'PENSAO_ALIMENTICIA',
                'name' => 'Pensão Alimentícia',
                'type' => 'deduction',
                'incidence_type' => 'legal',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto judicial de pensão alimentícia.',
            ],
            [
                'code' => 'DESCONTO_EPI',
                'name' => 'Desconto de EPI',
                'type' => 'deduction',
                'incidence_type' => 'deduction',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Desconto referente a EPI.',
            ],
            [
                'code' => 'OUTROS_DESCONTOS',
                'name' => 'Outros Descontos',
                'type' => 'deduction',
                'incidence_type' => 'deduction',
                'calculation_type' => 'manual',
                'affects_inss' => false,
                'affects_fgts' => false,
                'affects_irrf' => false,
                'affects_net' => true,
                'description' => 'Outros descontos da folha.',
            ],
        ];

        foreach ($items as $item) {
            PayrollEvent::updateOrCreate(
                ['code' => $item['code']],
                [
                    'name' => $item['name'],
                    'code' => $item['code'],
                    'type' => $item['type'],
                    'incidence_type' => $item['incidence_type'],
                    'calculation_type' => $item['calculation_type'],
                    'affects_inss' => $item['affects_inss'],
                    'affects_fgts' => $item['affects_fgts'],
                    'affects_irrf' => $item['affects_irrf'],
                    'affects_net' => $item['affects_net'],
                    'is_active' => true,
                    'description' => $item['description'],
                ]
            );
        }
    }
}